name: Repository Event Activity Types...

on:
    # push:
    #     branches:
    #         - main
    pull_request:
        branches:
            - main
    issues:
        types: [opened]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3