name: First Workflow.

on: [push]

jobs:
    run-shell-commands-1:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello! World"
            - name: multiline command
              run: |
                node -v
                npm -v
            - name: docker version
              run: |
                  docker --version
                  docker build -t connect:7.4.0-0.0.1 . -f Dockerfile
                  docker images
                  pwd
                   
    # run-shell-commands-2:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: echo a string
    #           run: echo "Hello! World"
    #         - name: multiline command
    #           run: |
    #             node -v
    #             npm -v

    # dependent-job-1:
    #     runs-on: ubuntu-latest
    #     needs: run-shell-commands-1
    #     steps:
    #         - name: echo a string
    #           run: echo "Hello! World"
    #         - name: multiline command
    #           run: |
    #             node -v
    #             npm -v

    # dependent-job-2:
    #     runs-on: ubuntu-latest
    #     needs: [run-shell-commands-1, run-shell-commands-2]
    #     steps:
    #         - name: echo a string
    #           run: echo "Hello! World"
    #         - name: multiline command
    #           run: |
    #             node -v
    #             npm -v
